# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

regexDemo <- function(s) {
    .Call('quanteda_regexDemo', PACKAGE = 'quanteda', s)
}

tokenizecpp <- function(x, sep, minLength, toLower, removeDigits, removePunct, removeTwitter, removeURL, removeAdditional) {
    .Call('quanteda_tokenizecpp', PACKAGE = 'quanteda', x, sep, minLength, toLower, removeDigits, removePunct, removeTwitter, removeURL, removeAdditional)
}

justTokenizeCpp <- function(x, sep, minLength) {
    .Call('quanteda_justTokenizeCpp', PACKAGE = 'quanteda', x, sep, minLength)
}

wordfishcpp <- function(wfm, dir, priors, tol) {
    .Call('quanteda_wordfishcpp', PACKAGE = 'quanteda', wfm, dir, priors, tol)
}

