# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tokenizecpp <- function(x, sep, minLength, toLower, removeDigits, removePunct, removeTwitter, removeURL, removeAdditional) {
    .Call('quanteda_tokenizecpp', PACKAGE = 'quanteda', x, sep, minLength, toLower, removeDigits, removePunct, removeTwitter, removeURL, removeAdditional)
}

